### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by geohot — COMMENTED** [review]
This is a worse pull request than Bitcoin Ocho.

**Comment by ghost** [comment]
You couldn't figure that out either.

**Comment by ghost** [comment]
Maybe you figure out metaphor with cash tag

**Comment by geohot** [comment]
I'm confused. DyingLlama is my hero.

https://www.youtube.com/channel/UC88oKpyXNid09t1m_PZlvfQ

**Pull request closed without merging**
