### PR TITLE
Goreport changes to get max score on go code

### PR DESCRIPTION
**Pull request by d6o**
Followed tips from [Go Report](https://goreportcard.com/report/github.com/geohot/lolrecaptcha) to get a max score

Executed `gofmt -s -w *.go` that simplified files and formatted then according [Go Style Guide](https://golang.org/doc/faq#Is_there_a_Go_programming_style_guide)

Added IDEA Project files to .gitignore

### CODE REVIEW

**Review by geohot — COMMENTED** [review]
I hate this 4 space or maybe tab shit. But if that's how you go that's how you go. l will learn more go tomorrow maybe.

**Comment by geohot** [comment]
I reread the pull request title and got excited when I heard I could get a maximum score. I love winning.

**Comment by geohot** [comment]
Okay, tried this in the morning. For serious I can't do tabs. Too terrible

**Comment by geohot** [comment]
Closed because tabs make me cry.

**Comment by d6o** [comment]
image

**Comment by geohot** [comment]
I know. I lost some respect for Richard Hendricks after that.

**Comment by odeke-em** [comment]
@geohot go comes with a tool called `go fmt` that automatically formats your code. It is used by pretty much every gopher and helps dissolve the tabs vs spaces argument :) You can read more about it at https://blog.golang.org/go-fmt-your-code.

For example take a look at:
* unformatted code on the playground https://play.golang.org/p/8tmUhCAzHh
* formatted code after hitting "Format" on that code https://play.golang.org/p/n_u5q4qiYw

You can use it your terminal by simply invoking `go fmt *.go` or in your directory `go fmt`.
```shell
$ cat << ! > outf.go && go fmt outf.go && cat outf.go
> package main
> import "fmt"
> func main() {
> fmt.Printf("hello there")
> }
> !
package main

import "fmt"

func main() {
	fmt.Printf("hello there")
}
```

After writing a bunch of code, I just `go fmt` it all and done.

It's cool that you are learning Go, hope you enjoy it!

**Pull request closed without merging**
